<template>
  <h1>{{ msg }}</h1>
  <ul>
    <li>{{ items[0] }}</li>
    <li>{{ items[1] }}</li>
    <li>{{ items[2] }}</li>
    <li>{{ items[3] }}</li>
    <li>{{ items[4] }}</li>
    <li>{{ items[5] }}</li>
    <li>{{ items[6] }}</li>
    <li>{{ items[7] }}</li>
    <li>{{ items[8] }}</li>
    <li>{{ items[9] }}</li>
    <li>{{ items[10] }}</li>
    <li>{{ items[11] }}</li>
    <li>{{ items[12] }}</li>
    <li>{{ items[13] }}</li>
    <li>{{ items[14] }}</li>
    <li>{{ items[15] }}</li>
    <li>{{ items[16] }}</li>
    <li>{{ items[17] }}</li>
    <li>{{ items[18] }}</li>
    <li>{{ items[19] }}</li>
    <li>{{ items[20] }}</li>
    <li>{{ items[21] }}</li>
    <li>{{ items[22] }}</li>
    <li>{{ items[23] }}</li>
    <li>{{ items[24] }}</li>
    <li>{{ items[25] }}</li>
    <li>{{ items[26] }}</li>
    <li>{{ items[27] }}</li>
    <li>{{ items[28] }}</li>
    <li>{{ items[29] }}</li>
    <li>{{ items[30] }}</li>
    <li>{{ items[31] }}</li>
    <li>{{ items[32] }}</li>
    <li>{{ items[33] }}</li>
    <li>{{ items[34] }}</li>
    <li>{{ items[35] }}</li>
    <li>{{ items[36] }}</li>
    <li>{{ items[37] }}</li>
    <li>{{ items[38] }}</li>
    <li>{{ items[39] }}</li>
    <li>{{ items[40] }}</li>
    <li>{{ items[41] }}</li>
    <li>{{ items[42] }}</li>
    <li>{{ items[43] }}</li>
    <li>{{ items[44] }}</li>
    <li>{{ items[45] }}</li>
    <li>{{ items[46] }}</li>
    <li>{{ items[47] }}</li>
    <li>{{ items[48] }}</li>
    <li>{{ items[49] }}</li>
    <li>{{ items[50] }}</li>
    <li>{{ items[51] }}</li>
    <li>{{ items[52] }}</li>
    <li>{{ items[53] }}</li>
    <li>{{ items[54] }}</li>
    <li>{{ items[55] }}</li>
    <li>{{ items[56] }}</li>
    <li>{{ items[57] }}</li>
    <li>{{ items[58] }}</li>
    <li>{{ items[59] }}</li>
    <li>{{ items[60] }}</li>
    <li>{{ items[61] }}</li>
    <li>{{ items[62] }}</li>
    <li>{{ items[63] }}</li>
    <li>{{ items[64] }}</li>
    <li>{{ items[65] }}</li>
    <li>{{ items[66] }}</li>
    <li>{{ items[67] }}</li>
    <li>{{ items[68] }}</li>
    <li>{{ items[69] }}</li>
    <li>{{ items[70] }}</li>
    <li>{{ items[71] }}</li>
    <li>{{ items[72] }}</li>
    <li>{{ items[73] }}</li>
    <li>{{ items[74] }}</li>
    <li>{{ items[75] }}</li>
    <li>{{ items[76] }}</li>
    <li>{{ items[77] }}</li>
    <li>{{ items[78] }}</li>
    <li>{{ items[79] }}</li>
    <li>{{ items[80] }}</li>
    <li>{{ items[81] }}</li>
    <li>{{ items[82] }}</li>
    <li>{{ items[83] }}</li>
    <li>{{ items[84] }}</li>
    <li>{{ items[85] }}</li>
    <li>{{ items[86] }}</li>
    <li>{{ items[87] }}</li>
    <li>{{ items[88] }}</li>
    <li>{{ items[89] }}</li>
    <li>{{ items[90] }}</li>
    <li>{{ items[91] }}</li>
    <li>{{ items[92] }}</li>
    <li>{{ items[93] }}</li>
    <li>{{ items[94] }}</li>
    <li>{{ items[95] }}</li>
    <li>{{ items[96] }}</li>
    <li>{{ items[97] }}</li>
    <li>{{ items[98] }}</li>
    <li>{{ items[99] }}</li>
  </ul>
</template>
<script>
export default {
  data() { return { msg: 'Hello, GetSampleData.com!', items: ["Item 0", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15", "Item 16", "Item 17", "Item 18", "Item 19", "Item 20", "Item 21", "Item 22", "Item 23", "Item 24", "Item 25", "Item 26", "Item 27", "Item 28", "Item 29", "Item 30", "Item 31", "Item 32", "Item 33", "Item 34", "Item 35", "Item 36", "Item 37", "Item 38", "Item 39", "Item 40", "Item 41", "Item 42", "Item 43", "Item 44", "Item 45", "Item 46", "Item 47", "Item 48", "Item 49", "Item 50", "Item 51", "Item 52", "Item 53", "Item 54", "Item 55", "Item 56", "Item 57", "Item 58", "Item 59", "Item 60", "Item 61", "Item 62", "Item 63", "Item 64", "Item 65", "Item 66", "Item 67", "Item 68", "Item 69", "Item 70", "Item 71", "Item 72", "Item 73", "Item 74", "Item 75", "Item 76", "Item 77", "Item 78", "Item 79", "Item 80", "Item 81", "Item 82", "Item 83", "Item 84", "Item 85", "Item 86", "Item 87", "Item 88", "Item 89", "Item 90", "Item 91", "Item 92", "Item 93", "Item 94", "Item 95", "Item 96", "Item 97", "Item 98", "Item 99"] } }
}
</script>
