FROM alpine:latest
RUN echo "step 0"
RUN echo "step 1"
RUN echo "step 2"
RUN echo "step 3"
RUN echo "step 4"
RUN echo "step 5"
RUN echo "step 6"
RUN echo "step 7"
RUN echo "step 8"
RUN echo "step 9"
RUN echo "step 10"
RUN echo "step 11"
RUN echo "step 12"
RUN echo "step 13"
RUN echo "step 14"
CMD ["echo", "Hello, GetSampleData.com!"]
