type Widget {
  id: ID!
  name: String!
  price: Float
  field0: String
  field1: String
  field2: String
  field3: String
  field4: String
  field5: String
  field6: String
  field7: String
  field8: String
  field9: String
  field10: String
  field11: String
  field12: String
  field13: String
  field14: String
  field15: String
  field16: String
  field17: String
  field18: String
  field19: String
  field20: String
  field21: String
  field22: String
  field23: String
  field24: String
  field25: String
  field26: String
  field27: String
  field28: String
  field29: String
  field30: String
  field31: String
  field32: String
  field33: String
  field34: String
  field35: String
  field36: String
  field37: String
  field38: String
  field39: String
  field40: String
  field41: String
  field42: String
  field43: String
  field44: String
  field45: String
  field46: String
  field47: String
  field48: String
  field49: String
  field50: String
  field51: String
  field52: String
  field53: String
  field54: String
  field55: String
  field56: String
  field57: String
  field58: String
  field59: String
  field60: String
  field61: String
  field62: String
  field63: String
  field64: String
  field65: String
  field66: String
  field67: String
  field68: String
  field69: String
  field70: String
  field71: String
  field72: String
  field73: String
  field74: String
  field75: String
  field76: String
  field77: String
  field78: String
  field79: String
  field80: String
  field81: String
  field82: String
  field83: String
  field84: String
  field85: String
  field86: String
  field87: String
  field88: String
  field89: String
  field90: String
  field91: String
  field92: String
  field93: String
  field94: String
  field95: String
  field96: String
  field97: String
  field98: String
  field99: String
  field100: String
  field101: String
  field102: String
  field103: String
  field104: String
  field105: String
  field106: String
  field107: String
  field108: String
  field109: String
  field110: String
  field111: String
  field112: String
  field113: String
  field114: String
  field115: String
  field116: String
  field117: String
  field118: String
  field119: String
  field120: String
  field121: String
  field122: String
  field123: String
  field124: String
  field125: String
  field126: String
  field127: String
  field128: String
  field129: String
  field130: String
  field131: String
  field132: String
  field133: String
  field134: String
  field135: String
  field136: String
  field137: String
  field138: String
  field139: String
  field140: String
  field141: String
  field142: String
  field143: String
  field144: String
  field145: String
  field146: String
  field147: String
  field148: String
  field149: String
  field150: String
  field151: String
  field152: String
  field153: String
  field154: String
  field155: String
  field156: String
  field157: String
  field158: String
  field159: String
  field160: String
  field161: String
  field162: String
  field163: String
  field164: String
  field165: String
  field166: String
  field167: String
  field168: String
  field169: String
  field170: String
  field171: String
  field172: String
  field173: String
  field174: String
  field175: String
  field176: String
  field177: String
  field178: String
  field179: String
  field180: String
  field181: String
  field182: String
  field183: String
  field184: String
  field185: String
  field186: String
  field187: String
  field188: String
  field189: String
  field190: String
  field191: String
  field192: String
  field193: String
  field194: String
  field195: String
  field196: String
  field197: String
  field198: String
  field199: String
  field200: String
  field201: String
  field202: String
  field203: String
  field204: String
  field205: String
  field206: String
  field207: String
  field208: String
  field209: String
  field210: String
  field211: String
  field212: String
  field213: String
  field214: String
  field215: String
  field216: String
  field217: String
  field218: String
  field219: String
  field220: String
  field221: String
  field222: String
  field223: String
  field224: String
  field225: String
  field226: String
  field227: String
  field228: String
  field229: String
  field230: String
  field231: String
  field232: String
  field233: String
  field234: String
  field235: String
  field236: String
  field237: String
  field238: String
  field239: String
  field240: String
  field241: String
  field242: String
  field243: String
  field244: String
  field245: String
  field246: String
  field247: String
  field248: String
  field249: String
  field250: String
  field251: String
  field252: String
  field253: String
  field254: String
  field255: String
  field256: String
  field257: String
  field258: String
  field259: String
  field260: String
  field261: String
  field262: String
  field263: String
  field264: String
  field265: String
  field266: String
  field267: String
  field268: String
  field269: String
  field270: String
  field271: String
  field272: String
  field273: String
  field274: String
  field275: String
  field276: String
  field277: String
  field278: String
  field279: String
  field280: String
  field281: String
  field282: String
  field283: String
  field284: String
  field285: String
  field286: String
  field287: String
  field288: String
  field289: String
  field290: String
  field291: String
  field292: String
  field293: String
  field294: String
  field295: String
  field296: String
  field297: String
  field298: String
  field299: String
  field300: String
  field301: String
  field302: String
  field303: String
  field304: String
  field305: String
  field306: String
  field307: String
  field308: String
  field309: String
  field310: String
  field311: String
  field312: String
  field313: String
  field314: String
  field315: String
  field316: String
  field317: String
  field318: String
  field319: String
  field320: String
  field321: String
  field322: String
  field323: String
  field324: String
  field325: String
  field326: String
  field327: String
  field328: String
  field329: String
  field330: String
  field331: String
  field332: String
  field333: String
  field334: String
  field335: String
  field336: String
  field337: String
  field338: String
  field339: String
  field340: String
  field341: String
  field342: String
  field343: String
  field344: String
  field345: String
  field346: String
  field347: String
  field348: String
  field349: String
  field350: String
  field351: String
  field352: String
  field353: String
  field354: String
  field355: String
  field356: String
  field357: String
  field358: String
  field359: String
  field360: String
  field361: String
  field362: String
  field363: String
  field364: String
  field365: String
  field366: String
  field367: String
  field368: String
  field369: String
  field370: String
  field371: String
  field372: String
  field373: String
  field374: String
  field375: String
  field376: String
  field377: String
  field378: String
  field379: String
  field380: String
  field381: String
  field382: String
  field383: String
  field384: String
  field385: String
  field386: String
  field387: String
  field388: String
  field389: String
  field390: String
  field391: String
  field392: String
  field393: String
  field394: String
  field395: String
  field396: String
  field397: String
  field398: String
  field399: String
  field400: String
  field401: String
  field402: String
  field403: String
  field404: String
  field405: String
  field406: String
  field407: String
  field408: String
  field409: String
  field410: String
  field411: String
  field412: String
  field413: String
  field414: String
  field415: String
  field416: String
  field417: String
  field418: String
  field419: String
  field420: String
  field421: String
  field422: String
  field423: String
  field424: String
  field425: String
  field426: String
  field427: String
  field428: String
  field429: String
  field430: String
  field431: String
  field432: String
  field433: String
  field434: String
  field435: String
  field436: String
  field437: String
  field438: String
  field439: String
  field440: String
  field441: String
  field442: String
  field443: String
  field444: String
  field445: String
  field446: String
  field447: String
  field448: String
  field449: String
  field450: String
  field451: String
  field452: String
  field453: String
  field454: String
  field455: String
  field456: String
  field457: String
  field458: String
  field459: String
  field460: String
  field461: String
  field462: String
  field463: String
  field464: String
  field465: String
  field466: String
  field467: String
  field468: String
  field469: String
  field470: String
  field471: String
  field472: String
  field473: String
  field474: String
  field475: String
  field476: String
  field477: String
  field478: String
  field479: String
  field480: String
  field481: String
  field482: String
  field483: String
  field484: String
  field485: String
  field486: String
  field487: String
  field488: String
  field489: String
  field490: String
  field491: String
  field492: String
  field493: String
  field494: String
  field495: String
  field496: String
  field497: String
  field498: String
  field499: String
  field500: String
  field501: String
  field502: String
  field503: String
  field504: String
  field505: String
  field506: String
  field507: String
  field508: String
  field509: String
  field510: String
  field511: String
  field512: String
  field513: String
  field514: String
  field515: String
  field516: String
  field517: String
  field518: String
  field519: String
  field520: String
  field521: String
  field522: String
  field523: String
  field524: String
  field525: String
  field526: String
  field527: String
  field528: String
  field529: String
  field530: String
  field531: String
  field532: String
  field533: String
  field534: String
  field535: String
  field536: String
  field537: String
  field538: String
  field539: String
  field540: String
  field541: String
  field542: String
  field543: String
  field544: String
  field545: String
  field546: String
  field547: String
  field548: String
  field549: String
  field550: String
  field551: String
  field552: String
  field553: String
  field554: String
  field555: String
  field556: String
  field557: String
  field558: String
  field559: String
  field560: String
  field561: String
  field562: String
  field563: String
  field564: String
  field565: String
  field566: String
  field567: String
  field568: String
  field569: String
  field570: String
  field571: String
  field572: String
  field573: String
  field574: String
  field575: String
  field576: String
  field577: String
  field578: String
  field579: String
  field580: String
  field581: String
  field582: String
  field583: String
  field584: String
  field585: String
  field586: String
  field587: String
  field588: String
  field589: String
  field590: String
  field591: String
  field592: String
  field593: String
  field594: String
  field595: String
  field596: String
  field597: String
  field598: String
  field599: String
  field600: String
  field601: String
  field602: String
  field603: String
  field604: String
  field605: String
  field606: String
  field607: String
  field608: String
  field609: String
  field610: String
  field611: String
  field612: String
  field613: String
  field614: String
  field615: String
  field616: String
  field617: String
  field618: String
  field619: String
  field620: String
  field621: String
  field622: String
  field623: String
  field624: String
  field625: String
  field626: String
  field627: String
  field628: String
  field629: String
  field630: String
  field631: String
  field632: String
  field633: String
  field634: String
  field635: String
  field636: String
  field637: String
  field638: String
  field639: String
  field640: String
  field641: String
  field642: String
  field643: String
  field644: String
  field645: String
  field646: String
  field647: String
  field648: String
  field649: String
  field650: String
  field651: String
  field652: String
  field653: String
  field654: String
  field655: String
  field656: String
  field657: String
  field658: String
  field659: String
  field660: String
  field661: String
  field662: String
  field663: String
  field664: String
  field665: String
  field666: String
  field667: String
  field668: String
  field669: String
  field670: String
  field671: String
  field672: String
  field673: String
  field674: String
  field675: String
  field676: String
  field677: String
  field678: String
  field679: String
  field680: String
  field681: String
  field682: String
  field683: String
  field684: String
  field685: String
  field686: String
  field687: String
  field688: String
  field689: String
  field690: String
  field691: String
  field692: String
  field693: String
  field694: String
  field695: String
  field696: String
  field697: String
  field698: String
  field699: String
  field700: String
  field701: String
  field702: String
  field703: String
  field704: String
  field705: String
  field706: String
  field707: String
  field708: String
  field709: String
  field710: String
  field711: String
  field712: String
  field713: String
  field714: String
  field715: String
  field716: String
  field717: String
  field718: String
  field719: String
  field720: String
  field721: String
  field722: String
  field723: String
  field724: String
  field725: String
  field726: String
  field727: String
  field728: String
  field729: String
  field730: String
  field731: String
  field732: String
  field733: String
  field734: String
  field735: String
  field736: String
  field737: String
  field738: String
  field739: String
  field740: String
  field741: String
  field742: String
  field743: String
  field744: String
  field745: String
  field746: String
  field747: String
  field748: String
  field749: String
  field750: String
  field751: String
  field752: String
  field753: String
  field754: String
  field755: String
  field756: String
  field757: String
  field758: String
  field759: String
  field760: String
  field761: String
  field762: String
  field763: String
  field764: String
  field765: String
  field766: String
  field767: String
  field768: String
  field769: String
  field770: String
  field771: String
  field772: String
  field773: String
  field774: String
  field775: String
  field776: String
  field777: String
  field778: String
  field779: String
  field780: String
  field781: String
  field782: String
  field783: String
  field784: String
  field785: String
  field786: String
  field787: String
  field788: String
  field789: String
  field790: String
  field791: String
  field792: String
  field793: String
  field794: String
  field795: String
  field796: String
  field797: String
  field798: String
  field799: String
  field800: String
  field801: String
  field802: String
  field803: String
  field804: String
  field805: String
  field806: String
  field807: String
  field808: String
  field809: String
  field810: String
  field811: String
  field812: String
  field813: String
  field814: String
  field815: String
  field816: String
  field817: String
  field818: String
  field819: String
  field820: String
  field821: String
  field822: String
  field823: String
  field824: String
  field825: String
  field826: String
  field827: String
  field828: String
  field829: String
  field830: String
  field831: String
  field832: String
  field833: String
  field834: String
  field835: String
  field836: String
  field837: String
  field838: String
  field839: String
  field840: String
  field841: String
  field842: String
  field843: String
  field844: String
  field845: String
  field846: String
  field847: String
  field848: String
  field849: String
  field850: String
  field851: String
  field852: String
  field853: String
  field854: String
  field855: String
  field856: String
  field857: String
  field858: String
  field859: String
  field860: String
  field861: String
  field862: String
  field863: String
  field864: String
  field865: String
  field866: String
  field867: String
  field868: String
  field869: String
  field870: String
  field871: String
  field872: String
  field873: String
  field874: String
  field875: String
  field876: String
  field877: String
  field878: String
  field879: String
  field880: String
  field881: String
  field882: String
  field883: String
  field884: String
  field885: String
  field886: String
  field887: String
  field888: String
  field889: String
  field890: String
  field891: String
  field892: String
  field893: String
  field894: String
  field895: String
  field896: String
  field897: String
  field898: String
  field899: String
  field900: String
  field901: String
  field902: String
  field903: String
  field904: String
  field905: String
  field906: String
  field907: String
  field908: String
  field909: String
  field910: String
  field911: String
  field912: String
  field913: String
  field914: String
  field915: String
  field916: String
  field917: String
  field918: String
  field919: String
  field920: String
  field921: String
  field922: String
  field923: String
  field924: String
  field925: String
  field926: String
  field927: String
  field928: String
  field929: String
  field930: String
  field931: String
  field932: String
  field933: String
  field934: String
  field935: String
  field936: String
  field937: String
  field938: String
  field939: String
  field940: String
  field941: String
  field942: String
  field943: String
  field944: String
  field945: String
  field946: String
  field947: String
  field948: String
  field949: String
  field950: String
  field951: String
  field952: String
  field953: String
  field954: String
  field955: String
  field956: String
  field957: String
  field958: String
  field959: String
  field960: String
  field961: String
  field962: String
  field963: String
  field964: String
  field965: String
  field966: String
  field967: String
  field968: String
  field969: String
  field970: String
  field971: String
  field972: String
  field973: String
  field974: String
  field975: String
  field976: String
  field977: String
  field978: String
  field979: String
  field980: String
  field981: String
  field982: String
  field983: String
  field984: String
  field985: String
  field986: String
  field987: String
  field988: String
  field989: String
  field990: String
  field991: String
  field992: String
  field993: String
  field994: String
  field995: String
  field996: String
  field997: String
  field998: String
  field999: String
}

type Query {
  widgets: [Widget]
}
