syntax = "proto3";

message Widget {
  int32 id = 1;
  string name = 2;
  float price = 3;
  string field0 = 10;
  string field1 = 11;
  string field2 = 12;
  string field3 = 13;
  string field4 = 14;
  string field5 = 15;
  string field6 = 16;
  string field7 = 17;
  string field8 = 18;
  string field9 = 19;
  string field10 = 20;
  string field11 = 21;
  string field12 = 22;
  string field13 = 23;
  string field14 = 24;
  string field15 = 25;
  string field16 = 26;
  string field17 = 27;
  string field18 = 28;
  string field19 = 29;
  string field20 = 30;
  string field21 = 31;
  string field22 = 32;
  string field23 = 33;
  string field24 = 34;
  string field25 = 35;
  string field26 = 36;
  string field27 = 37;
  string field28 = 38;
  string field29 = 39;
  string field30 = 40;
  string field31 = 41;
  string field32 = 42;
  string field33 = 43;
  string field34 = 44;
  string field35 = 45;
  string field36 = 46;
  string field37 = 47;
  string field38 = 48;
  string field39 = 49;
}
