syntax = "proto3";

message Widget {
  int32 id = 1;
  string name = 2;
  float price = 3;
  string field0 = 10;
  string field1 = 11;
  string field2 = 12;
  string field3 = 13;
  string field4 = 14;
  string field5 = 15;
  string field6 = 16;
  string field7 = 17;
  string field8 = 18;
  string field9 = 19;
  string field10 = 20;
  string field11 = 21;
  string field12 = 22;
  string field13 = 23;
  string field14 = 24;
  string field15 = 25;
  string field16 = 26;
  string field17 = 27;
  string field18 = 28;
  string field19 = 29;
  string field20 = 30;
  string field21 = 31;
  string field22 = 32;
  string field23 = 33;
  string field24 = 34;
  string field25 = 35;
  string field26 = 36;
  string field27 = 37;
  string field28 = 38;
  string field29 = 39;
  string field30 = 40;
  string field31 = 41;
  string field32 = 42;
  string field33 = 43;
  string field34 = 44;
  string field35 = 45;
  string field36 = 46;
  string field37 = 47;
  string field38 = 48;
  string field39 = 49;
  string field40 = 50;
  string field41 = 51;
  string field42 = 52;
  string field43 = 53;
  string field44 = 54;
  string field45 = 55;
  string field46 = 56;
  string field47 = 57;
  string field48 = 58;
  string field49 = 59;
  string field50 = 60;
  string field51 = 61;
  string field52 = 62;
  string field53 = 63;
  string field54 = 64;
  string field55 = 65;
  string field56 = 66;
  string field57 = 67;
  string field58 = 68;
  string field59 = 69;
  string field60 = 70;
  string field61 = 71;
  string field62 = 72;
  string field63 = 73;
  string field64 = 74;
  string field65 = 75;
  string field66 = 76;
  string field67 = 77;
  string field68 = 78;
  string field69 = 79;
  string field70 = 80;
  string field71 = 81;
  string field72 = 82;
  string field73 = 83;
  string field74 = 84;
  string field75 = 85;
  string field76 = 86;
  string field77 = 87;
  string field78 = 88;
  string field79 = 89;
  string field80 = 90;
  string field81 = 91;
  string field82 = 92;
  string field83 = 93;
  string field84 = 94;
  string field85 = 95;
  string field86 = 96;
  string field87 = 97;
  string field88 = 98;
  string field89 = 99;
  string field90 = 100;
  string field91 = 101;
  string field92 = 102;
  string field93 = 103;
  string field94 = 104;
  string field95 = 105;
  string field96 = 106;
  string field97 = 107;
  string field98 = 108;
  string field99 = 109;
}
